# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'dldemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dldemo
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'ReachabilitySwift'
  pod 'GoogleMaps'
  pod 'NotificationBannerSwift'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  
  target 'dldemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
